### ISSUE TITLE
screen tearing when increasing normal speed (120%) of PAL games

### ISSUE THREAD

**Issue by yhusei** [TheRhysWyrill/XBSX2#13]
when i increase normal speed to 120% in "pal" games to get 25 to 30fps i get screen tearing on xbox series s. The vsync option of the emulator does not solve the problem.

**Comment by TheRhysWyrill** [comment]
You're running a game at a non-native speed, I think that's what's causing the issue, if you want to eliminate that issue you'll have to run the game at native speed.

**Comment by yhusei** [comment]
yes, but both on pc and android this problem does not happen, since
this method is a way to obtain 60fps in "pal" versions. I hope you can
review it in the future, thanks.
