### ISSUE TITLE
Dead or Alive 2 randomly crashes

### ISSUE THREAD

**Issue by antoniodesousa** [TheRhysWyrill/XBSX2#16]
## Description

Dead or Alive 2 randomly crashes during the matches. All settings are the default.

### Expected behavior

No crashes during a match.

### Actual behavior

The game randomly crashes during a match. I noticed that the whole game layout disappears right before the game crashes.

### Steps to reproduce the bug

1. Launch the game
2. Pick a character in story mode
3. The game will crash at some point during a match

### Console
[Xbox Series S]

**Comment by mansoor909** [comment]
The cause of the problem is Direct3D 12
Tested on PC and Xbox
The solution is currently Direct3D 11

**Comment by antoniodesousa** [comment]
Indeed, it doesn't crash using Direct3D 11. The character's shadow is kinda messed up.

**Comment by TheRhysWyrill** [comment]
> Indeed, it doesn't crash using Direct3D 11. The character's shadow is kinda messed up.

Is this still an issue on the recent releases?

**Comment by antoniodesousa** [comment]
Yes, it was still crashing when using Direct3D 12 up until the latest release [26-9-2022](https://github.com/TheRhysWyrill/XBSX2/releases/tag/26-09-2022). I will test the latest release from today as soon as I can.

**Comment by TheRhysWyrill** [comment]
> Yes, it was still crashing when using Direct3D 12 up until the latest release [26-9-2022](https://github.com/TheRhysWyrill/XBSX2/releases/tag/26-09-2022). I will test the latest release from today as soon as I can.

I don't understand this issue, at this point i've played through all of the DoA2 "Story" with every character and experienced 0 crashes.

**Comment by antoniodesousa** [comment]
I will try to grab the error log (if any) if it still happens in the new release. Hopefully is fixed.

**Comment by antoniodesousa** [comment]
It still crashes using D3D 12 in the latest release from yesterday. I checked the **emulog.txt** and it's empty. And yes, I enabled logging in the settings and restart the app.

**Title:** DOA2: Hardcore
**Came ID:** SLUS-20071
**CRC:** 23AF6876

The game works fine using D3D 11 (besides the character weird shadows). You can close the ticket if you think is not worth investing time in finding out why it crashes using D3D 12.

**Comment by TheRhysWyrill** [comment]
I've had several other users test this exact same game and CRC and none of them have reported a D3D12 crash at any point regardless of the build(s) they tested so I'm not entirely sure what the issue is.
