### ISSUE TITLE
Splashdown polygon glitch on hardware mode

### ISSUE THREAD

**Issue by antoniodesousa** [TheRhysWyrill/XBSX2#18]
## Description

When running Splashdown on hardware mode and start a race, the whole screen becomes a total polygon mess. Software mode works perfectly though. I read that the sequel Rides Gone Wild used to have the same issue but it was fixed at some point.

### Expected behavior

No polygon mess when start a race using hardware mode.

### Actual behavior

The whole screen is a polygon mess when starting a race in hardware mode.

### Steps to reproduce the bug

1. Launch the game in hardware mode
2. Start any race
3. The whole screen is a polygon mess

### Console
[Xbox Series S]

**Comment by mansoor909** [comment]
Known Issues
Polygons glitch

    Status: Active
    Type: Serious
    Description: Starting a race will result in extreme slowdown and polygons covering the screen.
    Workaround: Use software mode.

https://wiki.pcsx2.net/Splashdown
