### ISSUE TITLE
Call Of Duty 3 randomly crashes

### ISSUE THREAD

**Issue by WujekFoliarz** [TheRhysWyrill/XBSX2#19]
After playing about 5-8 minutes the game randomly crashes, I've tried D3D11 but it didnt fix anything

Xbox Series S

**Comment by TheRhysWyrill** [comment]
> 

I recently did a test for this and made through the first and 2nd level without any sort of crash, I'd recommend disabling VSync, I've noticed it seems to be causing issues with performance/app stability.

**Comment by WujekFoliarz** [comment]
> > 
> 
> I recently did a test for this and made through the first and 2nd level without any sort of crash, I'd recommend disabling VSync, I've noticed it seems to be causing issues with performance/app stability.

well I only tried online multiplayer, maybe it only crashes when playing online

**Comment by TheRhysWyrill** [comment]
This might have been one of those crashes tied to FastCDVD or GPU Palette Conversion.
