### ISSUE TITLE
Haunting Ground

### ISSUE THREAD

**Issue by bideg** [TheRhysWyrill/XBSX2#22]
## Description

In hardware mode, text that is placed inside text boxes is being cut off at the edges where there should be a fade effect. This does not occur on the Windows version of PCSX2 in hardware mode.

### Expected behavior

There should be a fade effect on the edges of text boxes.

### Actual behavior

There is no fade effect on the edges of text boxes. Where the effect should be, the text is cut off.

### Steps to reproduce the bug

1. Start de game (PAL or NTSC version).
2. On the first screens, the issue can be found (even before title screen).

### Console
[Xbox Series S]

**Comment by TheRhysWyrill** [comment]
Use D3D11.
