### ISSUE TITLE
Games are not detected on USB drive

### ISSUE THREAD

**Issue by bfunk-tt** [TheRhysWyrill/XBSX2#26]
## Description

When games are stored on a USB 3.0 drive in a folder, and that folder is added to the Search Directory list, the games list is empty at startup until re-scanning the folder

### Expected behavior

The game list should be populated with games.

### Actual behavior

The game list is empty

### Steps to reproduce the bug

1. Install XBSX2 in retail mode
2. Place ISO files in a folder on a USB 3.0 drive formatted NTFS
3. Add the directory to the list of Search Directories and scan. The list is populated.
4. Quit the emulator and re-start it
5. The list of games is empty

### Console
Xbox Series S
![IMG_4140](https://user-images.githubusercontent.com/97177720/189924261-f9db47f5-67a1-4133-8fb8-6de62fe27ab8.jpg)
![IMG_4142](https://user-images.githubusercontent.com/97177720/189924259-ef993a11-0efc-4f1e-b919-ed3a61669cd6.jpg)
![IMG_4143](https://user-images.githubusercontent.com/97177720/189924256-a98fffb0-cc25-4d4b-926c-81309b95a84d.jpg)

**Comment by TheRhysWyrill** [comment]
Do this behavior still occur on the latest release?

**Comment by SolidParas** [comment]
I have the same problem on my external hdd but if i quit the app through the exit option (from the app not the Xbox) and re enter it will load the games normally

**Comment by TheRhysWyrill** [comment]
> I have the same problem on my external hdd but if i quit the app through the exit option (from the app not the Xbox) and re enter it will load the games normally

This behavior is something I've not been able to replicate so I can't exactly say what the cause of this issue is, are you on the latest version?

**Comment by TheRhysWyrill** [comment]
Myself and multiple others have been unable to replicate this issue so will assume it's fixed.
