### ISSUE TITLE
Taking code from private branches and removing copyright

### ISSUE THREAD

**Issue by stenzek** [TheRhysWyrill/XBSX2#27]
I've been informed that you guys are taking code from my development branches which isn't completed, or even PR'ed/merged in PCSX2 yet.

I would appreciate if you didn't, and furthermore, stop removing PCSX2 copyright from files, as seen here:

https://github.com/TheRhysWyrill/XBSX2/commit/8a65b1894220eb86e603fcaca9db5b00ff222220#diff-a453c8b011029a2bea1471e60bda69eef6d6c3d7c29af4a5bb922464d9a3cbb0L2

As the code is LGPL licensed, you have the right to reuse/modify it, but the original authors retain copyright. See section 7(b) of the GPL.

Furthermore, files like this are not LGPL licensed, since they have no license header, and are not part of PCSX2 yet. When it is merged, copyright gets transferred to PCSX2 and it's fine, but not prior, e.g. <https://github.com/TheRhysWyrill/XBSX2/blob/xbsx2/common/HeterogeneousContainers.h> / < https://github.com/TheRhysWyrill/XBSX2/blob/xbsx2/common/MemorySettingsInterface.cpp> / etc.

Edit: Before you use the "but it's GPL" argument, this code was never distributed by myself, the viral nature of the GPL applies when you're distributing it, not working on it alone in (semi)-private.

**Comment by TheRhysWyrill** [comment]
> I've been informed that you guys are taking code from my development branches which isn't completed, or even PR'ed/merged in PCSX2 yet.
> 
> I would appreciate if you didn't, and furthermore, stop removing PCSX2 copyright from files, as seen here:
> 
> [8a65b18#diff-a453c8b011029a2bea1471e60bda69eef6d6c3d7c29af4a5bb922464d9a3cbb0L2](https://github.com/TheRhysWyrill/XBSX2/commit/8a65b1894220eb86e603fcaca9db5b00ff222220#diff-a453c8b011029a2bea1471e60bda69eef6d6c3d7c29af4a5bb922464d9a3cbb0L2)
> 
> As the code is LGPL licensed, you have the right to reuse/modify it, but the original authors retain copyright. See section 7(b) of the GPL.
> 
> Furthermore, files like this are not LGPL licensed, since they have no license header, and are not part of PCSX2 yet. When it is merged, copyright gets transferred to PCSX2 and it's fine, but not prior, e.g. https://github.com/TheRhysWyrill/XBSX2/blob/xbsx2/common/HeterogeneousContainers.h / < [https://github.com/TheRhysWyrill/XBSX2/blob/xbsx2/common/MemorySettingsInterface.cpp>](https://github.com/TheRhysWyrill/XBSX2/blob/xbsx2/common/MemorySettingsInterface.cpp%3E) / etc.
> 
> Edit: Before you use the "but it's GPL" argument, this code was never distributed by myself, the viral nature of the GPL applies when you're distributing it, not working on it alone in (semi)-private.

Understood, my apologies to you and the PCSX2 Dev Team for removing the copyright from associated files, I'll add it back to all relevant files and rectify the other changes when I next have time, I thought removing the copyright would be the better option but I see now how wrong that choice was.

I will also stop adding code from in-progress branches, my apologies again. Just so I know for future reference, it's alright to take the code and implement it into this from the open PRs of PCSX2?
