### ISSUE TITLE
Fast boot option per game

### ISSUE THREAD

**Issue by ojt1998** [TheRhysWyrill/XBSX2#5]
On a previous version from another dev (no naming names) if you went on the menu for each individual game you choose fast boot for that one runtime only. Would it be possible for this version to have that feature added in?

Alternatively could the fast boot option per game be gotten to work? I have tried enabling it however the system doesn't respond to the state of this setting only the one in general settings. 

Ultimately I imagine this would be low priority and it's more so I can have the nostalgic sound of the PS2 boot but I also need to be able to play games from other regions.

Many thanks for your hard work

**Comment by TheRhysWyrill** [comment]
Sure, I could always add the "Slow Boot" option back to the list of items on Game Settings menu, I mostly removed it due to it being a feature I never used 😅

**Comment by ojt1998** [comment]
That would be great - it’s purely for my nostalgia trip hearing the PS2 boot sounds so being able to select would be perfect. Thank you 😊


Oliver Taylor
Case and Cabinet Designer and Manufacturer | Ultrasonics Flightcases Ltd.
E-mail: ***@***.***
Phone: 01472 236224
Website: www.ultrasonicscases.co.uk
Ultrasonics Flightcases Limited is registered in England.
Reg. No. 09040195
VAT No. 167 1874 78

Please consider the environment before printing this email.

Please note that Ultrasonics Flightcases may monitor email traffic data and also the content of email for the purposes of security and staff training.

All sales are subject to our terms and conditions found on our website. Please take note of these or contact your representative should you have any queries.

This message contains confidential information and is intended only for the named Recipients. If you are not the intended recipient you should not disseminate, distribute or copy this e-mail. Please notify Oliver Taylor immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Ultrasonics Flightcases therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.

All quotes from Ultrasonics Flightcases are valid for 14 days following the date of email transmission unless otherwise stated

**Comment by TheRhysWyrill** [comment]
@ojt1998 Can you confirm whether this issue is solved with the latest release?

**Comment by ojt1998** [comment]
Yes it's all working now - thank you so much!
