### ISSUE TITLE
God of war 2 fog transparency issue 

### ISSUE THREAD

**Issue by lostless** [TheRhysWyrill/XBSX2#8]
## Description

Anything that’s in the fog it’s like the z buffer is messed up.  In the first scene, You can see the colossus or soldiers through walls if the walls hiding them are in the fog. 

### Expected behavior

Walls should hide things

### Actual behavior

Read above 

### Steps to reproduce the bug

start the game to the first set piece.  You’ll see the issue when the camera zooms out from the soldiers and when they enter the fog, they go in front of the gate.  And then the colossus shows through.

### Console
[Xbox series S]

**Comment by mansoor909** [comment]
AMD GPU problem solved
In pcsx2 v1.7.3267
https://github.com/PCSX2/pcsx2/pull/6931

**Comment by TheRhysWyrill** [comment]
As the above comment mentions, this was fixed with that commit which has now been backported into XBSX2.
