### ISSUE TITLE
unable to delete key bindings in settings

### ISSUE THREAD

**Issue by 123monge** [TheRhysWyrill/XBSX2#9]
## Description

[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Console
[Xbox One/Series X|S]

**Comment by Acidragon** [comment]
@TheRhysWyrill So is there now a way to delete the current mappings (without manually editing the ini file)? Would also be nice to be able to map the xbox guide button also. 

Thank you!

**Comment by TheRhysWyrill** [comment]
@Acidragon There is indeed, I fixed the Reset Settings button on the Controller Settings tab as using that results in an unusable controller and then also made a Reset Settings button on the Hotkey Settings tab to reset hotkeys, they'll be available on the next release which should be at some point this weekend 🙂

As for mapping the guide button that's unfortunately not a possibility.

**Comment by TheRhysWyrill** [comment]
Solved with the latest update.
